### ISSUE TITLE
client.set with time not expire after incr(with passcode)

### ISSUE THREAD

**Issue by liyangshiren** [jaysonsantos/python-binary-memcached#240]
docker run -p 11231:11211 -it -d --name test_memcached3 -e MEMCACHED_USERNAME=my_user -e MEMCACHED_PASSWORD=my_password bitnami/memcached:latest
=====pip install================
pip install python-binary-memcached
=======python script==============
import bmemcached

client = bmemcached.Client('127.0.0.1:11231', 'my_user', 'my_password')
client.set('user_id', 1, time=2)

if __name__ == "__main__":
    while True:
        client.incr('user_id', 1)
        hints = client.get('user_id')
        print('hints:', hints)

=======issue=======
hints will never be none

Compare with normal without passcode
======
docker run -p 11221:11211 -it -d --name test_memcached2 bitnami/memcached:latest
======
pip install python-memcached 
======
import memcache

client = memcache.Client(['127.0.0.1:11221'], debug=0)
client.set('user_id', 1, 2)
if __name__ == "__main__":
    while True:
        client.incr('user_id', 1)
        hints = client.get('user_id')
        print('hints:', hints)
=====issue====
hints will be None after 2 seconds

**Comment by jaysonsantos** [comment]
Hey there, I am going to close this because the two libraries implement different protocols.
I just checked the binary spec [1] and it says that expire time is mandatory, and you can override the expiration on incr method [2].
Unless I am seeing something wrong there? If I'd set the expiration time to `0xffffffff` and the key does not exist, it would return a not found error.
To be honest, it's been a while I deal with these kinds of things on memcached, and IIRC, they had the binary protocol deprecated.
[1] https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped#increment-decrement
[2] https://github.com/jaysonsantos/python-binary-memcached/blob/master/bmemcached/client/replicating.py#L235
